### PR TITLE
Always show the profile picker if there are 2 or more profiles configured

### PR DESCRIPTION
**Pull request by bjfletcher**
I've found myself always needing to click "Profiles" to switch profiles. I thought, why not always show the profile picker if there are 2 or more profiles configured? Meaning only 2 clicks needed to switch profiles, rather than 3. 👍 

image

### CODE REVIEW

**Comment by bjfletcher** [comment]
Note that this branches off the other PR

**Comment by GlynnPhillips** [comment]
Thanks @bjfletcher I am a little concerned about this one though. My reason is that I have seen people with lots of profiles so I would like to understand if this would be irritating for them. Especially as the layout for the profile picker in its current state is not ideal

**Comment by bjfletcher** [comment]
The nice poll in our channel suggests 6 profiles is the most people have.  Seems ok.  E.g.:

image

**Comment by GlynnPhillips** [comment]
@bjfletcher Yeah I am not sure some people voted on the poll because I have certainly worked with people who have LOTS of profile 😃 however I have come around to the idea and it can always be improved in the future if it does cause issues for people

**Pull request merged**
